import 'package:intl/intl.dart';

class ProductDatabaseModel {
  const ProductDatabaseModel({
    required this.productName,
    required this.productImage,
    required this.brandName,
    required this.vendorName,
    required this.ourCost,
    required this.salePrice,
    required this.createdBy,
    required this.creadtedDate,
    required this.status,
    this.updatedBy,
    this.updatedDate,
  });

  final String productName;
  final String productImage;
  final String brandName;
  final String vendorName;
  final double ourCost;
  final double salePrice;
  final DateTime creadtedDate;
  final String createdBy;
  final DateTime? updatedDate;
  final String? updatedBy;
  final String status;

  get details => null;
}

DateTime? convertStringToDate(String dateString) {
  try {
    DateFormat formate = DateFormat('dd/MM/yyyy hh:mm a');
    return formate.parse(dateString);
  } catch (e) {
    return null;
  }
}

final now = DateTime.now();

final List<ProductDatabaseModel> dummyProductList = [
  ProductDatabaseModel(
      productName: 'Classic Denim Jacket',
      productImage: 'imageName',
      brandName: 'Urban Threads',
      vendorName: 'CottonCloud Creations',
      ourCost: 119.99,
      salePrice: 189.75,
      createdBy: 'John Smith',
      creadtedDate: convertStringToDate('22/10/2024 11:45 AM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Casual T-Shirt',
      productImage: 'imageName',
      brandName: 'Chic & Co.',
      vendorName: 'Sole Symphony',
      ourCost: 245.50,
      salePrice: 325.00,
      createdBy: 'Emma Johnson',
      creadtedDate: convertStringToDate('19/10/2024 04:50 PM') ?? now,
      updatedDate: convertStringToDate('25/10/2024 11:45 AM') ?? now,
      updatedBy: 'Girish Chauhan',
      status: 'Active'),
  ProductDatabaseModel(
      productName: 'Formal Button-Up Shirt',
      productImage: 'imageName',
      brandName: 'Casual Classics',
      vendorName: 'TeeTrendz',
      ourCost: 189.75,
      salePrice: 199.50,
      createdBy: 'Tejas Daftary',
      creadtedDate: convertStringToDate('12/10/2024 03:35 PM') ?? now,
      status: 'InActive'),
  ProductDatabaseModel(
      productName: 'Leather Sneakers',
      productImage: 'imageName',
      brandName: 'Trendy Tees',
      vendorName: 'Thread & Thimble',
      ourCost: 325.00,
      salePrice: 356.00,
      createdBy: 'Michael Brown',
      creadtedDate: convertStringToDate('19/10/2024 11:45 AM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Sporty Track Pant',
      productImage: 'imageName',
      brandName: 'Classic Styles',
      vendorName: 'Urban Stitch',
      ourCost: 150.99,
      salePrice: 156.00,
      createdBy: 'Olivia Davis',
      creadtedDate: convertStringToDate('30/09/2024 06:55 PM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Lightweight Windbreaker',
      productImage: 'imageName',
      brandName: 'Fashion Forward',
      vendorName: 'Graphic Grove',
      ourCost: 275.30,
      salePrice: 306.00,
      createdBy: 'William Miller',
      creadtedDate: convertStringToDate('07/10/2024 11:45 AM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Graphic Tee',
      productImage: 'imageName',
      brandName: 'Dynamic Wear',
      vendorName: 'ChromaCotton',
      ourCost: 399.00,
      salePrice: 456.00,
      createdBy: 'Ava Wilson',
      creadtedDate: convertStringToDate('16/10/2024 07:15 PM') ?? now,
      updatedDate: convertStringToDate('19/10/2024 11:45 AM') ?? now,
      updatedBy: 'Victoria Cooper',
      status: 'Active'),
  ProductDatabaseModel(
      productName: 'Cotton Polo Shirt',
      productImage: 'imageName',
      brandName: 'Cozy Comforts',
      vendorName: 'StyleSpectrum',
      ourCost: 102.45,
      salePrice: 125.00,
      createdBy: 'James Taylor',
      creadtedDate: convertStringToDate('11/09/2024 01:05 PM') ?? now,
      status: 'InActive'),
  ProductDatabaseModel(
      productName: 'Comfortable Sweatpants',
      productImage: 'imageName',
      brandName: 'Elegant Attire',
      vendorName: 'PrintParadise',
      ourCost: 213.60,
      salePrice: 256.00,
      createdBy: 'Sophia Anderson',
      creadtedDate: convertStringToDate('17/10/2024 08:45 AM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Elegant Blazer',
      productImage: 'imageName',
      brandName: 'Bold Steps',
      vendorName: 'CasualCanvas',
      ourCost: 167.80,
      salePrice: 176.00,
      createdBy: 'Benjamin Thomas',
      creadtedDate: convertStringToDate('22/10/2024 11:45 AM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Chic Maxi Dress',
      productImage: 'imageName',
      brandName: 'Essential Essentials',
      vendorName: 'FreshFabric Co.',
      ourCost: 358.25,
      salePrice: 359.00,
      createdBy: 'Mia Jackson',
      creadtedDate: convertStringToDate('23/09/2024 07:20 PM  ') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Stylish Ankle Boots',
      productImage: 'imageName',
      brandName: 'Retro Rewind',
      vendorName: 'StepWise Footwear',
      ourCost: 123.90,
      salePrice: 156.00,
      createdBy: 'Lucas White',
      creadtedDate: convertStringToDate('02/10/2024 04:40 PM') ?? now,
      updatedDate: convertStringToDate('22/10/2024 11:45 AM') ?? now,
      updatedBy: 'Tejas Daftary',
      status: 'Active'),
  ProductDatabaseModel(
      productName: 'Vintage Bomber Jacket',
      productImage: 'imageName',
      brandName: 'Everyday Elegance',
      vendorName: 'KickCraft',
      ourCost: 289.99,
      salePrice: 325.00,
      createdBy: 'Tejas Daftary',
      creadtedDate: convertStringToDate('15/09/2024 06:30 PM') ?? now,
      status: 'InActive'),
  ProductDatabaseModel(
      productName: 'Athletic Shorts',
      productImage: 'imageName',
      brandName: 'Vibrant Vibes',
      vendorName: 'Stride & Style',
      ourCost: 175.60,
      salePrice: 185.00,
      createdBy: 'Isabella Harris',
      creadtedDate: convertStringToDate('10/10/2024 08:25 AM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Floral Summer Dress',
      productImage: 'imageName',
      brandName: 'Street Smart',
      vendorName: 'Urban Sole',
      ourCost: 333.33,
      salePrice: 356.00,
      createdBy: 'Tejas Daftary',
      creadtedDate: convertStringToDate('27/09/2024 05:55 PM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Trendy Hooded Sweatshirt',
      productImage: 'imageName',
      brandName: 'Simply Stylish',
      vendorName: 'Glide Gear',
      ourCost: 204.10,
      salePrice: 251.00,
      createdBy: 'Mason Martin',
      creadtedDate: convertStringToDate('31/10/2024 10:15 AM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Classic Chinos',
      productImage: 'imageName',
      brandName: 'Active Edge',
      vendorName: 'FitFoot Finds',
      ourCost: 299.95,
      salePrice: 316.00,
      createdBy: 'Charlotte Thompson',
      creadtedDate: convertStringToDate('01/10/2024 07:45 PM') ?? now,
      updatedDate: convertStringToDate('08/10/2024 09:50 AM') ?? now,
      updatedBy: 'Jack Bell',
      status: 'Active'),
  ProductDatabaseModel(
      productName: 'Slip-On Canvas Shoes',
      productImage: 'imageName',
      brandName: 'Luxe Layers',
      vendorName: 'Trendy Treads',
      ourCost: 112.20,
      salePrice: 126.00,
      createdBy: 'Ethan Garcia',
      creadtedDate: convertStringToDate('19/09/2024 03:55 PM') ?? now,
      status: 'InActive'),
  ProductDatabaseModel(
      productName: 'Knit Cardigan',
      productImage: 'imageName',
      brandName: 'Timeless Trends',
      vendorName: 'Sneaker Sphere',
      ourCost: 245.75,
      salePrice: 256.00,
      createdBy: 'Amelia Martinez',
      creadtedDate: convertStringToDate('11/10/2024 11:05 AM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Tailored Dress Shirt',
      productImage: 'imageName',
      brandName: 'Playful Prints',
      vendorName: 'LushLaces',
      ourCost: 379.85,
      salePrice: 326.00,
      createdBy: 'Alexander Robinson',
      creadtedDate: convertStringToDate('18/10/2024 05:40 PM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Running Sneakers',
      productImage: 'imageName',
      brandName: 'Modern Fit',
      vendorName: 'Apex Outerwear',
      ourCost: 134.99,
      salePrice: 153.00,
      createdBy: 'Harper Clark',
      creadtedDate: convertStringToDate('30/10/2024 04:50 PM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Casual Slip-Ons',
      productImage: 'imageName',
      brandName: 'Savvy Styles',
      vendorName: 'CozyCove Jackets',
      ourCost: 219.40,
      salePrice: 226.00,
      createdBy: 'Daniel Lewis',
      creadtedDate: convertStringToDate('21/10/2024 02:55 PM') ?? now,
      updatedDate: convertStringToDate('26/10/2024 11:45 AM') ?? now,
      updatedBy: 'Hannah Morgan',
      status: 'Active'),
  ProductDatabaseModel(
      productName: 'Puffer Jacket',
      productImage: 'imageName',
      brandName: 'Iconic Wear',
      vendorName: 'Bold & Brave Coats',
      ourCost: 290.00,
      salePrice: 296.00,
      createdBy: 'Evelyn Lee',
      creadtedDate: convertStringToDate('22/10/2024 11:45 AM') ?? now,
      status: 'InActive'),
  ProductDatabaseModel(
      productName: 'Linen Short Sleeve Shirt',
      productImage: 'imageName',
      brandName: 'Rugged Threads',
      vendorName: 'Jacket Junction',
      ourCost: 350.50,
      salePrice: 367.00,
      createdBy: 'Henry Walker',
      creadtedDate: convertStringToDate('01/11/2024 02:45 PM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'High-Waisted Jeans',
      productImage: 'imageName',
      brandName: 'Charmed Clothing',
      vendorName: 'WindWhisper Wear',
      ourCost: 175.25,
      salePrice: 186.00,
      createdBy: 'Abigail Hall',
      creadtedDate: convertStringToDate('08/09/2024 11:15 AM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Beach Cover-Up',
      productImage: 'imageName',
      brandName: 'Smooth Silhouettes',
      vendorName: 'Layered Luxe',
      ourCost: 115.00,
      salePrice: 121.00,
      createdBy: 'Samuel Allen',
      creadtedDate: convertStringToDate('05/11/2024 08:10 AM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Faux Leather Leggings',
      productImage: 'imageName',
      brandName: 'Eclectic Apparel',
      vendorName: 'Chilly Chic',
      ourCost: 389.99,
      salePrice: 397.00,
      createdBy: 'Ella Young',
      creadtedDate: convertStringToDate('21/11/2024 02:00 PM') ?? now,
      updatedDate: convertStringToDate('22/12/2024 11:45 AM') ?? now,
      updatedBy: 'Luke Rogers',
      status: 'Active'),
  ProductDatabaseModel(
      productName: 'Sporty Baseball Cap',
      productImage: 'imageName',
      brandName: 'Dynamic Duds',
      vendorName: 'FleeceFusion',
      ourCost: 200.99,
      salePrice: 211.00,
      createdBy: 'David King',
      creadtedDate: convertStringToDate('04/12/2024 09:00 AM') ?? now,
      status: 'InActive'),
  ProductDatabaseModel(
      productName: 'Plaid Flannel Shirt',
      productImage: 'imageName',
      brandName: 'Refined Basics',
      vendorName: 'Urban Armor',
      ourCost: 268.45,
      salePrice: 270.00,
      createdBy: 'Grace Wright',
      creadtedDate: convertStringToDate('29/10/2024 03:25 PM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Thermal Henley',
      productImage: 'imageName',
      brandName: 'Sleek Styles',
      vendorName: 'SleekShells',
      ourCost: 340.10,
      salePrice: 401.00,
      createdBy: 'Joseph Scott',
      creadtedDate: convertStringToDate('11/09/2024 01:05 PM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Wool Overcoat',
      productImage: 'imageName',
      brandName: 'Effortless Fashion',
      vendorName: 'AllSeason Attire',
      ourCost: 199.50,
      salePrice: 208.00,
      createdBy: 'Scarlett Torres',
      creadtedDate: convertStringToDate('09/11/2024 10:50 AM') ?? now,
      status: 'Draft'),
  ProductDatabaseModel(
      productName: 'Softshell Jacket',
      productImage: 'imageName',
      brandName: 'Mountain Gear',
      vendorName: 'StyleSavvy Boutique',
      ourCost: 389.00,
      salePrice: 409.00,
      createdBy: 'Gabriel Nguyen',
      creadtedDate: convertStringToDate('13/12/2024 05:30 PM') ?? now,
      updatedDate: convertStringToDate('18/12/2024 11:45 AM') ?? now,
      updatedBy: 'Ryan Cook',
      status: 'Active'),
  ProductDatabaseModel(
      productName: 'Ripped Skinny Jeans',
      productImage: 'imageName',
      brandName: 'Coastal Casuals',
      vendorName: 'TrendSet Threads',
      ourCost: 126.75,
      salePrice: 135.00,
      createdBy: 'Aria Carter',
      creadtedDate: convertStringToDate('17/10/2024 08:45 AM') ?? now,
      status: 'InActive'),
  ProductDatabaseModel(
      productName: 'Comfy Pajama Set',
      productImage: 'imageName',
      brandName: 'Sporty Chic',
      vendorName: 'Wardrobe Wonders',
      ourCost: 310.25,
      salePrice: 324.00,
      createdBy: 'Anthony Perez',
      creadtedDate: convertStringToDate('14/11/2024 12:15 PM') ?? now,
      status: 'Draft'),
];
